name: Build mod
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: unzip AutoTrapdoor.zip
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 9.2.0
      - run: gradle build
        working-directory: AutoTrapdoor
      - uses: actions/upload-artifact@v4
        with:
          name: autotrapdoor-jar
          path: |
            AutoTrapdoor/build/libs/*.jar
            !AutoTrapdoor/build/libs/*-sources.jar
